### ISSUE TITLE
Wired controllers, GP2040-CE

### ISSUE THREAD

**Issue by Soundtoxin** [Ibrahim778/8BitVita#12]
Does this plugin also support using the additional controllers in a wired configuration? The readme seems to focus on Bluetooth, so I couldn't tell.

I am also curious if support for controllers running the GP2040-CE firmware could be added. This covers a few physical controllers, usually arcade/fight sticks, powered by things like the Raspberry Pi Pico. For example, the [Flatbox](https://github.com/jfedor2/flatbox) [Rev 5](https://github.com/jfedor2/flatbox/tree/master/hardware-rev5).
This firmware has various modes to be compatible with many different platforms, like PC, Switch, PS3, etc. The DInput mode for PS3 does not seem to be working on the Vita TV, and I wonder if it's because of the Vita TV being stricter than the PS3 about which controllers are supported. If this is the issue, perhaps a homebrew plugin could solve it.

I have an issue open in the GP2040-CE repo about getting the controller working as well.

https://github.com/OpenStickCommunity/GP2040-CE/issues/328

Apologies if this is not the place to post about this since it's not an 8bitdo controller.

**Comment by Ibrahim778** [comment]
This plugin is bluetooth only and can't do anything with a wired connection.
You'd have a better chance for wired controllers asking here: https://github.com/isage/vixen
