### ISSUE TITLE
Adrenaline Settings bug

### ISSUE THREAD

**Issue by Xfade81** [Ibrahim778/8BitVita#5]
Noticed a weird bug when in Adrenaline in combination with sn30 Pro+

When you hold the home button while in Adrenaline on the 8bitdo controller you go to the PS Vita menu. When you tap down twice to go to Adrenaline Settings and press X it puts my Vita TV into standby.
On screen you can see the cursor move to the settings button but it still does standby. This does not happen with a Dualshock 4. When you use that, it actually enters the Settings menu.

**Comment by Ibrahim778** [comment]
This is because of the timing between PS Button presses. This is as good as it'll get I'm afraid.
