### ISSUE TITLE
X1vita (There is no option, in its corresponding place.)

### ISSUE THREAD

**Issue by ViTaXXX** [Ibrahim778/8BitVita#7]
Hello, I have a curious question.

In ps vita with x1vita and with an xbox one controller, and with games that need RT LT, how do I get RT and LT to work?

The triggers do not work (the idea is to use moonlight with the xbox one controller, and that RT and LT work)

In short, making RT/LT work in games.

Any ideas?

**Comment by Ibrahim778** [comment]
Odd how it doesn't work. Everything worked fine last I checked?
Use the companion -> Debug, Press the buttons that don't work (ONLY THOSE DON'T MOVE THE JOYSTICKS).
And send a screenshot of what's on the screen.

**Comment by Ibrahim778** [comment]
Also this issue is in the wrong place?????
Use X1Vita for Xbox one controllers. Not 8bitvita

**Comment by ViTaXXX** [comment]
I was referring to xb1, as the ps vita does not have R2 / L2 (RT / LT), it does not detect those buttons in games (for example emulators that do need those buttons).

**Comment by Ibrahim778** [comment]
> Use the companion -> Debug, Press the buttons that don't work (ONLY THOSE DON'T MOVE THE JOYSTICKS).
> And send a screenshot of what's on the screen.

Do this.

**Comment by ViTaXXX** [comment]
solved. close it thanks
